export default [
  { text0: 'Love and affection', text1: 'Cash money baby!' },
  { text0: 'What I want you got', text1: 'might be hard to handle' },
  { text0: 'Him', text1: 'Her' },
  { text0: 'Plato', text1: 'Play-doh' },
  {
    text0: 'Finishing something successfully',
    text1: 'Wasting all my time dithering about',
  },
  { text0: 'Waiting for', text1: 'Godot' },
  { text0: 'Being cheeky', text1: 'Being real' },
  {
    text0: "Wait it's always turtles?",
    text1: 'Always has been, all the way down',
  },
  { text0: "Uh oh I've been caught", text1: '...' },
  { text0: 'Carry on my', text1: 'wayward son' },
  { text0: 'No one', text1: "could've predicted this" },
  { text0: 'Sid', text1: 'Spencer' },
  { text0: 'Front end', text1: 'Back end' },
  { text0: 'Me', text1: 'My friends' },
  { text0: 'What if Oscar Wilde', text1: 'was around to chill' },
  { text0: "Who's better than badboy?", text1: 'Nooooobody' },
  { text0: 'When he is just so good at chess', text1: '' },
  { text0: 'Drawn pawn endgame', text1: 'mouseslip' },
  { text0: 'Ice cream', text1: 'water butter' },
  { text0: 'I want to know', text1: 'less' },
  { text0: 'My dignity', text1: 'How delicious licking the plate will be' },
  { text0: "Here's to you", text1: 'the dreamers!' },
  { text0: 'Goals and ambitions', text1: 'dessert menu' },
  { text0: 'Oasis in the desert', text1: 'Oasis the band' },
  { text0: 'My oh my', text1: 'that was simply too much' },
  { text0: 'Sir', text1: 'Do you mind' },
  { text0: 'Maam', text1: "This is a Wendy's" },
  { text0: 'No one must know', text1: 'my real taste in music' },
  { text0: 'Modern love', text1: 'old vitriol' },
  { text0: 'The dream has gone', text1: 'but the baby is real' },
  { text0: 'Pasta', text1: 'a gluten bomb' },
  { text0: 'Simply', text1: 'Marvelous' },
  {
    text0: 'It puts the lotion on its skin',
    text1: 'Or else... well you know',
  },
  { text0: 'What is love', text1: "baby don't hurt me" },
  { text0: 'Chilling', text1: 'Grilling' },
  { text0: 'Not to worry', text1: "I'm trained in flexbox" },
  { text0: 'My life', text1: 'bootcamp' },
  { text0: 'Complete disbelief', text1: 'Complete lucidity' },
  { text0: 'Be the change you wish to', text1: 'find in the couch' },
  { text0: 'We hate it when', text1: 'Our friends become successful' },
  { text0: "Couldn't be me", text1: 'King' },
  { text0: 'It is what it is', text1: '' },
  { text0: 'Generic aphorisms', text1: 'Politicians' },
  { text0: 'Pass the salt', text1: 'I want a divorce' },
  { text0: 'Notorious B.I.G.', text1: 'Infamous smol' },
  {
    text0: 'If you must throw stones in a glass house',
    text1: 'throw them at the ceiling',
  },
  { text0: 'Oy', text1: 'Bruv' },
  { text0: 'Disney', text1: 'Real life' },
  { text0: 'Merit', text1: 'Charm' },
  { text0: '9-5', text1: 'A life at sea' },
];
